services:
  postgres:
    image: postgres:16-alpine
    container_name: task-tracker-db
    environment:
      POSTGRES_DB: task_tracker_db
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-tracker-network

volumes:
  postgres_data:

networks:
  task-tracker-network:
    driver: bridge